import sys
import cv2 as cv
import os
import numpy as np
from PyQt5.QtWidgets import QApplication, QDialog, QFileDialog
from PyQt5 import QtCore, QtGui, QtWidgets
from ui import *

class Ui_Form(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1700, 1200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 190, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.right_spin = QtWidgets.QSpinBox(self.centralwidget)
        self.right_spin.setGeometry(QtCore.QRect(380, 120, 431, 51))
        self.right_spin.setMaximum(10000)
        self.right_spin.setObjectName("right_spin")
        self.bias_6 = QtWidgets.QSpinBox(self.centralwidget)
        self.bias_6.setGeometry(QtCore.QRect(590, 800, 211, 41))
        self.bias_6.setPrefix("")
        self.bias_6.setMaximum(10000)
        self.bias_6.setObjectName("bias_6")
        self.center_x_spin = QtWidgets.QSpinBox(self.centralwidget)
        self.center_x_spin.setGeometry(QtCore.QRect(380, 330, 431, 51))
        self.center_x_spin.setMaximum(10000)
        self.center_x_spin.setObjectName("center_x_spin")
        self.min_slider = QtWidgets.QSlider(self.centralwidget)
        self.min_slider.setGeometry(QtCore.QRect(20, 1020, 1441, 31))
        self.min_slider.setOrientation(QtCore.Qt.Horizontal)
        self.min_slider.setObjectName("min_slider")
        self.bias_3 = QtWidgets.QSpinBox(self.centralwidget)
        self.bias_3.setGeometry(QtCore.QRect(590, 710, 211, 41))
        self.bias_3.setPrefix("")
        self.bias_3.setMaximum(10000)
        self.bias_3.setObjectName("bias_3")
        self.open_folder_button = QtWidgets.QPushButton(self.centralwidget)
        self.open_folder_button.setGeometry(QtCore.QRect(920, 60, 691, 61))
        self.open_folder_button.setObjectName("open_folder_button")
        self.bias_1 = QtWidgets.QSpinBox(self.centralwidget)
        self.bias_1.setGeometry(QtCore.QRect(20, 710, 201, 41))
        self.bias_1.setPrefix("")
        self.bias_1.setMaximum(10000)
        self.bias_1.setObjectName("bias_1")
        self.center_y_spin = QtWidgets.QSpinBox(self.centralwidget)
        self.center_y_spin.setGeometry(QtCore.QRect(380, 400, 431, 51))
        self.center_y_spin.setMaximum(10000)
        self.center_y_spin.setObjectName("center_y_spin")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 400, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.r_spin = QtWidgets.QSpinBox(self.centralwidget)
        self.r_spin.setGeometry(QtCore.QRect(380, 470, 431, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r_spin.sizePolicy().hasHeightForWidth())
        self.r_spin.setSizePolicy(sizePolicy)
        self.r_spin.setMaximum(10000)
        self.r_spin.setObjectName("r_spin")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 330, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.bias_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.bias_2.setGeometry(QtCore.QRect(300, 710, 201, 41))
        self.bias_2.setPrefix("")
        self.bias_2.setMaximum(10000)
        self.bias_2.setObjectName("bias_2")
        self.bias_7 = QtWidgets.QSpinBox(self.centralwidget)
        self.bias_7.setGeometry(QtCore.QRect(20, 890, 201, 41))
        self.bias_7.setPrefix("")
        self.bias_7.setMaximum(10000)
        self.bias_7.setObjectName("bias_7")
        self.count_label = QtWidgets.QLineEdit(self.centralwidget)
        self.count_label.setGeometry(QtCore.QRect(930, 700, 681, 231))
        self.count_label.setObjectName("count_label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.next_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_button.setGeometry(QtCore.QRect(920, 460, 691, 61))
        self.next_button.setObjectName("next_button")
        self.bias_4 = QtWidgets.QSpinBox(self.centralwidget)
        self.bias_4.setGeometry(QtCore.QRect(20, 800, 201, 41))
        self.bias_4.setPrefix("")
        self.bias_4.setMaximum(10000)
        self.bias_4.setObjectName("bias_4")
        self.up_spin = QtWidgets.QSpinBox(self.centralwidget)
        self.up_spin.setGeometry(QtCore.QRect(380, 190, 431, 51))
        self.up_spin.setMaximum(10000)
        self.up_spin.setObjectName("up_spin")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 60, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.min_spin = QtWidgets.QSpinBox(self.centralwidget)
        self.min_spin.setGeometry(QtCore.QRect(1500, 1000, 111, 51))
        self.min_spin.setMaximum(10000)
        self.min_spin.setObjectName("min_spin")
        self.max_spin = QtWidgets.QSpinBox(self.centralwidget)
        self.max_spin.setGeometry(QtCore.QRect(1500, 1080, 111, 51))
        self.max_spin.setMaximum(10000)
        self.max_spin.setObjectName("max_spin")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 260, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.left_spin = QtWidgets.QSpinBox(self.centralwidget)
        self.left_spin.setGeometry(QtCore.QRect(380, 50, 431, 51))
        self.left_spin.setMaximum(10000)
        self.left_spin.setObjectName("left_spin")
        self.bias_5 = QtWidgets.QSpinBox(self.centralwidget)
        self.bias_5.setGeometry(QtCore.QRect(300, 800, 201, 41))
        self.bias_5.setPrefix("")
        self.bias_5.setMaximum(10000)
        self.bias_5.setObjectName("bias_5")
        self.bias_8 = QtWidgets.QSpinBox(self.centralwidget)
        self.bias_8.setGeometry(QtCore.QRect(300, 890, 201, 41))
        self.bias_8.setPrefix("")
        self.bias_8.setMaximum(10000)
        self.bias_8.setObjectName("bias_8")
        self.pre_button = QtWidgets.QPushButton(self.centralwidget)
        self.pre_button.setGeometry(QtCore.QRect(920, 260, 691, 61))
        self.pre_button.setObjectName("pre_button")
        self.max_slider = QtWidgets.QSlider(self.centralwidget)
        self.max_slider.setGeometry(QtCore.QRect(20, 1100, 1441, 31))
        self.max_slider.setOrientation(QtCore.Qt.Horizontal)
        self.max_slider.setObjectName("max_slider")
        self.down_spin = QtWidgets.QSpinBox(self.centralwidget)
        self.down_spin.setGeometry(QtCore.QRect(380, 260, 431, 51))
        self.down_spin.setMaximum(10000)
        self.down_spin.setObjectName("down_spin")
        self.bias_9 = QtWidgets.QSpinBox(self.centralwidget)
        self.bias_9.setGeometry(QtCore.QRect(590, 890, 211, 41))
        self.bias_9.setPrefix("")
        self.bias_9.setMaximum(10000)
        self.bias_9.setObjectName("bias_9")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 470, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        #MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1700, 20))
        self.menubar.setObjectName("menubar")
        #MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "UP"))
        self.open_folder_button.setText(_translate("MainWindow", "Open Folder"))
        self.label_6.setText(_translate("MainWindow", "Center_Y"))
        self.label_5.setText(_translate("MainWindow", "Center_x"))
        self.count_label.setText(_translate("MainWindow", "The total is:"))
        self.label_2.setText(_translate("MainWindow", "RIGHT"))
        self.next_button.setText(_translate("MainWindow", "Next"))
        self.label.setText(_translate("MainWindow", "LEFT"))
        self.label_4.setText(_translate("MainWindow", "DOWN"))
        self.pre_button.setText(_translate("MainWindow", "Previous"))
        self.label_7.setText(_translate("MainWindow", "Radius"))
